"""empty message

Revision ID: a9231e6a0c52
Revises: bcf1bb6aed58
Create Date: 2016-03-25 10:18:08.398952

"""

# revision identifiers, used by Alembic.
revision = 'a9231e6a0c52'
down_revision = 'bcf1bb6aed58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('text_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'text_html')
    ### end Alembic commands ###
