"""empty message

Revision ID: d53df544c988
Revises: a9231e6a0c52
Create Date: 2016-03-25 10:51:20.425703

"""

# revision identifiers, used by Alembic.
revision = 'd53df544c988'
down_revision = 'a9231e6a0c52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
